- hosts: localhost
  vars:
    - host_wwns_map_input_data: {}

  tasks:
    
  #- name: Load Host Properties
   #   include_vars: 'properties/host_properties/host_properties.yml'

    #environment:
       # no_proxy: "{{storage_system_ip}}"

    - set_fact:
        host_wwns_map_input_data: >
                                     {
                                       "host_wwpns_map": [
                                         {
                                              "name": "ANSIBLE_Test_HOST_ESXi",
                                              "wwpns": [
                                                 "51402EC0128AB123",
                                                 "51402EC0128AB12A"
                                               ]
                                          }
                                        ]
                                       }

    - set_fact:
        host_wwns_map_data: "{{ host_wwns_map_input_data | from_json }}"

    - debug:
        msg: "{{ host_wwns_map_data.host_wwpns_map }}"

    - name: Create Host "{{ host_name }}"
      hpe3par_host:
        storage_system_ip: "{{ storage_system_ip }}"
        storage_system_username: "{{ storage_system_username }}"
        storage_system_password: "{{ storage_system_password }}"
        state: present
        host_name: "{{ host_name }}"
        host_fc_wwns: "{{ item.wwpns }}"
      loop: "{{ host_wwns_map_data.host_wwpns_map }}"
