- hosts: localhost
  tasks:
    - name: Load Volume properties
      include_vars: 'properties/host_properties/host_properties.yml'

      #environment:
       # no_proxy: "{{storage_system_ip}}"

    - name: Delete Host "{{ host_name }}"
      hpe3par_host:
        storage_system_ip: "{{ storage_system_ip }}"
        storage_system_username: "{{ storage_system_username }}"
        storage_system_password: "{{ storage_system_password }}"
        state: absent
        host_name: "{{ host_name }}"
