- hosts: localhost
  tasks:

    #- name: Load Storage System Properties
    #  include_vars: 'properties/storege_system_properties/storage_system_properties.yml'

    - name: Load Volume Properties
      include_vars: 'properties/3par_volume_properties/volume_properties.yml'

      environment:
        no_proxy: "{{storage_system_ip}}"

    - name: Grow Volume "{{ volume_name }} by "{{ updated_size }}" {{ size_unit }}"
      hpe3par_volume:
        storage_system_ip: "{{ storage_system_ip }}"
        storage_system_username: "{{ storage_system_username }}"
        storage_system_password: "{{ storage_system_password }}"
        state: grow
        volume_name: "{{ volume_name }}"
        size: "{{ updated_size }}"
        size_unit: "{{ size_unit }}"
