- hosts: localhost
  tasks:
  - name: Load Storage System Properties
      include_vars: 'properties/storege_system_properties/storage_system_properties.yml'

    - name: Load Volume Properties
      include_vars: 'properties/3par_volume_properties/volume_properties.yml'
      
    - name: Load Host Properties
      include_vars: 'properties/3par_volume_properties/volume_properties.yml'

    - name: Load VCenter Vars
      include_vars: 'properties/vmware_properties/vcenter_server_properties.yml'

      #environment:
       # no_proxy: "{{storage_system_ip}}"

  - name: remote copy group status
    hpe3par_remote_copy:
      storage_system_ip: "{{ storage_system_ip }}"
      storage_system_password: "{{ storage_system_password }}"
      storage_system_username: "{{ storage_system_username }}"
      state: remote_copy_status
      remote_copy_group_name: "{{ rcg_name }}"
    register: result

  - debug:
      msg: "{{ result.output.remote_copy_sync_status}}"

  - name: Stop remote copy
    hpe3par_remote_copy:
      storage_system_ip: "{{ storage_system_ip }}"
      storage_system_password: "{{ storage_system_password }}"
      storage_system_username: "{{ storage_system_username }}"
      remote_copy_group_name: "{{ rcg_name }}"
      state: stop

  - name: Dismiss Remote Copy target
    hpe3par_remote_copy:
      storage_system_ip: "{{ storage_system_ip }}"
      storage_system_password: "{{ storage_system_password }}"
      storage_system_username: "{{ storage_system_username }}"
      remote_copy_group_name: "{{ rcg_name }}"
      state: dismiss_target
      target_name: A7200cR4U15

  